// Import all modules in correct order
import './lib.js'
import './spritesheet.js'
import './ecs.js'
import './tilemap.js'
import './ecs/components.js'
import './ecs/staticCollisionGrid.js'
import './ecs/systems/InputSystem.js'
import './ecs/systems/PhysicsSystem.js'
import './ecs/systems/CollisionSystem.js'
import './ecs/systems/AnimationSystem.js'
import './ecs/systems/RenderSystem.js'
import './ecs/systems/AudioSystem.js'
import './mario.js'
import './game.js'
